#!/usr/bin/env bash
# Prints the Homebrew formula for a release.
#
#   scripts/homebrew-formula.sh 0.2.0 SHA256SUMS.txt > Formula/rustclean.rb
#
# SHA256SUMS.txt is the checksum file attached to every GitHub release.
set -euo pipefail

version="${1:?usage: $0 VERSION SHA256SUMS}"
sums="${2:?usage: $0 VERSION SHA256SUMS}"
base="https://github.com/hzrbasaran/rustClean/releases/download/v${version}"

sha() {
  local file="rustclean-v${version}-$1.tar.gz"
  local sum
  sum=$(awk -v f="$file" '$2 == f || $2 == "*" f { print $1 }' "$sums")
  if [ -z "$sum" ]; then
    echo "no checksum for $file in $sums" >&2
    exit 1
  fi
  echo "$sum"
}

asset() {
  printf '      url "%s/rustclean-v%s-%s.tar.gz"\n' "$base" "$version" "$1"
  printf '      sha256 "%s"\n' "$(sha "$1")"
}

cat <<EOF
# Generated by scripts/homebrew-formula.sh in hzrbasaran/rustClean.
class Rustclean < Formula
  desc "Terminal disk usage analyzer and cleaner"
  homepage "https://github.com/hzrbasaran/rustClean"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
$(asset aarch64-apple-darwin)
    end
    on_intel do
$(asset x86_64-apple-darwin)
    end
  end

  on_linux do
    on_intel do
$(asset x86_64-unknown-linux-gnu)
    end
  end

  def install
    bin.install "rustclean"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rustclean --version")
  end
end
EOF
